services:
  dev:
    build:
      context: .
      target: dev
    ports:
      - "7777:5173"
    volumes:
      - .:/app
      - /app/node_modules
    profiles:
      - dev

  app:
    build:
      context: .
      target: production
    ports:
      - "8080:80"
    profiles:
      - prod
